In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [ ]:
df = pd.read_csv('movies_metadata.csv')

# **Data Preprocessing**

In [ ]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [ ]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30943 entries, 0 to 30942
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  30943 non-null  object
 1   belongs_to_collection  3460 non-null   object
 2   budget                 30943 non-null  object
 3   genres                 30943 non-null  object
 4   homepage               5032 non-null   object
 5   id                     30943 non-null  object
 6   imdb_id                30931 non-null  object
 7   original_language      30940 non-null  object
 8   original_title         30943 non-null  object
 9   overview               30572 non-null  object
 10  popularity             30939 non-null  float64
 11  poster_path            30774 non-null  object
 12  production_companies   30941 non-null  object
 13  production_countries   30941 non-null  object
 14  release_date           30910 non-null  object
 15  revenue                30939 non-null  float64
 16  runtime                30856 non-null  float64
 17  spoken_languages       30939 non-null  object
 18  status                 30894 non-null  object
 19  tagline                16183 non-null  object
 20  title                  30938 non-null  object
 21  video                  30938 non-null  object
 22  vote_average           30938 non-null  float64
 23  vote_count             30938 non-null  float64
dtypes: float64(5), object(19)
memory usage: 5.7+ MB

In [ ]:
df.shape

(30943, 24)

In [ ]:
df.isnull().sum()

adult                        0
belongs_to_collection    27483
budget                       0
genres                       0
homepage                 25911
id                           0
imdb_id                     12
original_language            3
original_title               0
overview                   371
popularity                   4
poster_path                169
production_companies         2
production_countries         2
release_date                33
revenue                      4
runtime                     87
spoken_languages             4
status                      49
tagline                  14760
title                        5
video                        5
vote_average                 5
vote_count                   5
dtype: int64

In [ ]:
# remove all duplicates.
df = df.drop_duplicates().reset_index(drop=True)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
# Takes columns which is only requires.
df = df[['title', 'overview', 'genres','tagline','vote_average','popularity']]

In [ ]:
df.head()

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",NaN,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",Still Yelling. Still Fighting. Still Ready for...,6.5,11.712900
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",Just When His World Is Back To Normal... He's ...,5.7,8.387519

In [ ]:
df.isnull().sum() # there is still null values

title               5
overview          371
genres              0
tagline         14752
vote_average        5
popularity          4
dtype: int64

In [ ]:
df = df.dropna(subset=['title']) # remove the titles which has no name or null values

In [ ]:
df['overview'] = df['overview'].fillna('') # leave blank space in null values

In [ ]:
df.iloc[0]['genres']

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [ ]:
# we extract the genres together in a list
import ast
df['genres'] = df['genres'].apply(lambda x :" ".join([i['name'] for i in ast.literal_eval(x)]))

In [ ]:
df['genres']

0         Animation Comedy Family
1        Adventure Fantasy Family
2                  Romance Comedy
3            Comedy Drama Romance
4                          Comedy
                   ...
30925               Horror Comedy
30926                 Documentary
30927            Family Animation
30928             Action Thriller
30929
Name: genres, Length: 30926, dtype: object

In [ ]:
# fill the tagline with empty space
df['tagline'] = df['tagline'].fillna('')

In [ ]:
df.isnull().sum() # now all columns and rows are clear

title           0
overview        0
genres          0
tagline         0
vote_average    0
popularity      0
dtype: int64

In [ ]:
# we combine overview, genres and tagline together
df['tags'] = df['overview'] + ' ' + df['genres'] + ' ' + df['tagline']

In [ ]:
df.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.712900,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,Just when George Banks has recovered from his ...

In [ ]:
df['tags'][1]

"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. Adventure Fantasy Family Roll the dice and unleash the excitement!"

# **NLP**

In [ ]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [ ]:
# download stopwords and wordnet
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [ ]:
stop_words = set(stopwords.words('english')) # set stopwords using variable
lemmatizer = WordNetLemmatizer()  # set lemmatizer using variable

In [ ]:
def preprocess_text(text):
  # convert text into lower case
  text = str(text).lower()

  # remove all punctuation
  text = re.sub(r'[^\w\s]', '', text)

  words = text.split()
  # remove stopwords
  words = [word for word in words if word not in stop_words]

  # lemmatize the words
  words = [lemmatizer.lemmatize(word) for word in words]

  return ' '.join(words)

In [ ]:
# now apply this function on tags
df['tags'] = df['tags'].apply(preprocess_text)

In [ ]:
df['tags'][1] # you can see all stopwords are removed

'sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult who trapped inside game 26 year living room alans hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creature adventure fantasy family roll dice unleash excitement'

In [ ]:
# reset all database
df = df.reset_index(drop=True)

In [ ]:
indices = pd.Series(df.index, index=df['title']).drop_duplicates()
indices

title
Toy Story                                    0
Jumanji                                      1
Grumpier Old Men                             2
Waiting to Exhale                            3
Father of the Bride Part II                  4
                                         ...
Gingerdead Man vs. Evil Bong             30921
Sirius                                   30922
Kung Fu Panda: Secrets of the Masters    30923
Bulletproof                              30924
Shelter Island                           30925
Length: 30926, dtype: int64

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf = TfidfVectorizer(max_features=50000,ngram_range=(1,2),stop_words='english')

In [ ]:
tfidf_matrix = tfidf.fit_transform(df['tags'])

In [ ]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1092279 stored elements and shape (30926, 50000)>

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
def recommend(title, n = 10):
  if title not in indices:
    return ['Movie not found']

  idx = indices[title]
  sim_score = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
  similar_idx = sim_score.argsort()[::-1][1:n+1]
  return df['title'].iloc[similar_idx]

In [ ]:
recommend('Avatar')

26547                                      Avatar 2
13883                          The Inhabited Island
26553                                Thor: Ragnarok
28633                          Stand by Me Doraemon
2457                                     The Matrix
7472                           Frank Herbert's Dune
28403                        France société anonyme
20372                                        Désiré
9949                             A Trip to the Moon
6414     Lara Croft Tomb Raider: The Cradle of Life
Name: title, dtype: object

In [ ]:
import pickle

pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl','wb'))

pickle.dump(indices,open('indices.pkl','wb'))

df.to_pickle('df.pkl')

pickle.dump(tfidf,open('tfidf.pkl','wb'))